remove PIPE_BIND_TRANSFER_READ/WRITE for compatibility with mesa 12.1
This changes are the necessary complement to corresponding
mesa commit 5981ab5 "gallium: remove PIPE_BIND_TRANSFER_READ/WRITE"

Fixes the following building errors:

external/drm_gralloc/gralloc_drm_pipe.c:102:11: error: use of undeclared identifier 'PIPE_BIND_TRANSFER_READ'
...
external/drm_gralloc/gralloc_drm_pipe.c:104:11: error: use of undeclared identifier 'PIPE_BIND_TRANSFER_WRITE'